{
 "title": "RabbitMQ",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(rabbitmq_running, instance)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(rabbitmq_running{instance=\"$instance\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status de RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://www.rabbitmq.com/assets/files/rabbitmq-logo-with-name-258baa7f7ef3862e8f0dfa09cb760f68.svg\"\n     alt=\"Rabbit Icone\"\n     style=\"float: left; margin: 10px;\" />"
   }
  },
  {
   "title": "Service  RabbitMQ ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_running{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory used (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=\"$instance\", node=~\"$node\"}/1024/1024"
    }
   ]
  },
  {
   "title": "Number of File Descriptor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\",job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "Number of Websoketd queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*websocket.*\"})"
    }
   ]
  },
  {
   "title": "Number of celey queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*celery.*\"})"
    }
   ]
  },
  {
   "title": "Number of wazo-confd queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*wazo-confd.*\"})"
    }
   ]
  },
  {
   "title": "Number of wazo-dird queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*wazo-dird.*\"})"
    }
   ]
  },
  {
   "title": "Number of wazo-chatd queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*wazo-chatd.*\"})"
    }
   ]
  },
  {
   "title": "Number of wazo-calld queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*wazo-calld.*\"})"
    }
   ]
  },
  { "title": "Utilisation de la mémoire", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory usage (percent)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_used{instance=\"$instance\", node=~\"$node\"}) by (node) / sum(rabbitmq_node_mem_limit{instance=\"$instance\",node=~\"$node\"}) by (node) * 100",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_used{instance=\"$instance\", node=~\"$node\"}) by (node) /1024/1024",
     "legendFormat": "MB"
    }
   ]
  },
  {
   "title": "Utilisation des FD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "Utilisation des File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "Max FDS"
    },
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Current FDS"
    }
   ]
  },
  {
   "title": "Utilisation du disque",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "Disk free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "min(rabbitmq_node_disk_free{instance=\"$instance\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{instance}}/{{node}}:free"
    },
    {
     "expr": "min(rabbitmq_node_disk_free_limit{instance=\"$instance\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{instance}}/{{node}}:limit"
    }
   ]
  },
  {
   "title": "Connections/Channels/Consumers state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections{instance=\"$instance\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": " channels and consumers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels{instance=\"$instance\"})",
     "legendFormat": "channels"
    },
    {
     "expr": "sum(rabbitmq_queue_consumers{instance=\"$instance\"})",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Websoketd queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true
  },
  {
   "title": "Number of Websocketd Queues and Messages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*websocket.*\"})",
     "legendFormat": "nb websocketd queues"
    },
    {
     "expr": "sum(rabbitmq_queue_messages{instance=\"$instance\", queue=~\".*websocket.*\"})",
     "legendFormat": "nb websocketd messages"
    }
   ]
  },
  {
   "title": "Number of Messages Websocketd per status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{instance=\"$instance\", queue=~\".*websocket.*\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_published_total{instance=\"$instance\", queue=~\".*websocket.*\"}[$__rate_interval]))",
     "legendFormat": "published"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_delivered_total{instance=\"$instance\", queue=~\".*websocket.*\"}[$__rate_interval]))",
     "legendFormat": "delivered"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged{instance=\"$instance\", queue=~\".*websocket.*\"})",
     "legendFormat": "unack"
    }
   ]
  },
  {
   "title": "Others queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true
  },
  {
   "title": "Messages per Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{instance=\"$instance\", queue!~\".*websocket.*\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Number of Messages per status (other queues)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rabbitmq_queue_messages_ready{instance=\"$instance\", queue!~\".*websocket.*\"}) by (queue)",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "max(rabbitmq_queue_messages_published_total{instance=\"$instance\", queue!~\".*websocket.*\"}) by (queue)",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "max(rabbitmq_queue_messages_delivered_total{instance=\"$instance\", queue!~\".*websocket.*\"}) by (queue)",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged{instance=\"$instance\", queue!~\".*websocket.*\"})",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  }
 ]
}