FROM nginx:1.25.2

RUN apt-get update && apt-get install -y vim
RUN mkdir /startup

COPY cluster.conf.tpl /startup/cluster.conf.tpl
COPY pilot.conf.tpl /startup/pilot.conf.tpl
COPY docker-entrypoint.sh /startup/docker-entrypoint.sh
COPY gen-lb-config.sh /startup/gen-lb-config.sh

COPY certs /etc/ssl/certs/

LABEL maintainer=__MAINTAINER__
LABEL image_status=__STATUS__

ENTRYPOINT [ "/startup/docker-entrypoint.sh" ]
