FROM nginx:1.25.2

RUN apt-get update && apt-get install -y vim

COPY cluster.conf /etc/nginx/conf.d/default.conf
COPY pilot.conf /etc/nginx/conf.d/pilot.conf
COPY nginx.conf.generated /etc/nginx/nginx.conf
COPY certs /etc/ssl/certs/

LABEL maintainer=__MAINTAINER__
LABEL image_status=__STATUS__
LABEL trafgen_nodes=__TRAFGEN_NODES__
LABEL containers_per_node=__CONTAINERS__
LABEL cluster_size=__CLUSTER_SIZE__

CMD [ "nginx", "-g", "'daemon off;'" ]
