#!/usr/bin/bash

TRAFGEN_IMAGE=${1:-trafgen-lb:2.0.3}
CONTAINER_NAME=${2:-trafgen-lb}
 
docker stop $CONTAINER_NAME  2>/dev/null
docker rm $CONTAINER_NAME  2>/dev/null

docker run -d -p 443:443 -p 9999:80 --rm \
	--name $CONTAINER_NAME \
	--env CONNECT_TIMEOUT=60 \
	--env READ_TIMEOUT=600 \
	--env TRAFGEN_NODES=1 \
	--env LAST_CONTAINER=9 \
	$TRAFGEN_IMAGE
