#!/usr/bin/bash

usage(){
    echo "Usage: semverctl <inc|dec|set> <patch|minor|major> <CURRENT_VERSION>" >&2
    echo "Example: semverctl inc patch 1.3.4" >&2
    echo "Example: semverctl dec patch 1.3.4" >&2
    echo "Example: semverctl set version 1.3.4" >&2
}

bump_version() {
    local action=$1
    local part=$2
    local version=$3

    IFS='.' read -ra VERSION_PARTS <<< "$version"
    
    major=${VERSION_PARTS[0]}
    minor=${VERSION_PARTS[1]}
    patch=${VERSION_PARTS[2]}

    case $action in
        "inc")
            case $part in
                "major")
                    major=$((major + 1))
                    minor=0
                    patch=0
                    ;;
                "minor")
                    minor=$((minor + 1))
                    patch=0
                    ;;
                "patch")
                    patch=$((patch + 1))
                    ;;
                *)
                    echo "Version part unknown: $part" >&2
                    usage
                    exit 1
                    ;;
            esac
            ;;
        "dec")
            case $part in
                "major")
                    major=$((major - 1))
                    minor=0
                    patch=0
                    ;;
                "minor")
                    if [ $minor -eq 0 ]; then
                        echo "Minor version is already 0. Cannot decrement further." >&2
                        exit 1
                    fi
                    minor=$((minor - 1))
                    patch=0
                    ;;
                "patch")
                    if [ $patch -eq 0 ]; then
                        echo "Patch version is already 0. Cannot decrement further." >&2
                        exit 1
                    fi
                    patch=$((patch - 1))
                    ;;
                *)
                    echo "Version part unknown: $part" >&2
                    usage
                    exit 1
                    ;;
            esac
            ;;
        "set")
            case $part in
                "version")
                    major=$major
                    minor=$minor
                    patch=$patch
                    ;;
            esac
            ;;
        *)
            echo "Unknown action: $action" >&2
            usage
            exit 1
            ;;
    esac

    NEW_VERSION="$major.$minor.$patch"
    echo $NEW_VERSION
}

if [ $# -ne 3 ]; then
    echo "Error: missing arguments" >&2
    usage
    exit 1
fi

ACTION=$1
SEMVER=$2
CURRENT_VERSION=$3

bump_version $ACTION $SEMVER $CURRENT_VERSION
