global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

    #remote_write:
    #- url: "http://172.16.43.106:8428/api/v1/write"
    #write_relabel_configs:

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'node_exporter_metrics'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.43.106:9090']

  - job_name: 'process_exporter'
    static_configs:
      - targets: ['172.16.43.33:9256', '172.16.43.109:9256', '172.16.43.242:9256', '172.16.43.235:9256', '172.16.43.193:9257','172.16.43.141:9257','172.16.43.39:9257']
        labels:
          ip: '172.16.43.33'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.16.43.33:9100', '172.16.43.109:9100', '172.16.43.242:9100', '172.16.43.235:9100', '172.16.43.193:9100', '172.16.43.141:9100', '172.16.43.34:9100', '172.16.43.48:9100','172.16.43.39:9100']
        labels:
          ip: '172.16.43.33'

  - job_name: 'asterisk'
    metrics_path: /api/asterisk/metrics 
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.16.43.242:443', '172.16.43.193:443','172.16.43.141:443','172.16.43.39:443']

  - job_name: 'asterisk_exporter'
    static_configs:
      - targets: ['172.16.43.33:5039','172.16.43.39:5039']
        labels:

  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['172.16.43.33:9419', '172.16.43.242:9419', '172.16.43.193:9419','172.16.43.141:9419','172.16.43.39:9419']
        labels:
          ip: '172.16.43.33'

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['172,16.43.33:9113', '172.16.43.235:9113','172.16.43.242:9113','172.16.43.141:9113','172.16.43.193:9113','172.16.43.39:9113']
        labels:
          ip: '172.16.43.33'

  - job_name: "nginx-fluentd"
    static_configs:
      - targets: ['172,16.43.33:24231', '172.16.43.235:24231','172.16.43.242:24231','172.16.43.141:24231','172.16.43.193:24231','172.16.43.39:24231']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['172.16.43.33:9187', '172.16.43.48:9187',  '172.16.43.141:9187','172.16.43.193:9187', '172.16.43.48:9187','172.16.43.39:9187']
        labels:
          ip: '172.16.43.33'

  - job_name: 'dird_exporter'
    metrics_path: /api/dird/0.1/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.16.43.33:443', '172.16.43.242:443', '172.16.43.141:443', '172.16.43.193:443','172.16.43.39:443']
        labels:
          framework: 'flask'
          service: 'dird'

  - job_name: 'calld_exporter'
    metrics_path: /api/calld/1.0/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.16.43.33:443', '172.16.43.242:443', '172.16.43.193:443', '172.16.43.141:443','172.16.43.39:443']
        labels:
          framework: 'flask'
          service: 'calld'

  - job_name: 'auth_exporter'
    metrics_path: /api/auth/0.1/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.16.43.109:443', '172.16.43.33:443', '172.16.43.242:443', '172.16.43.141:443', '172.16.43.193:443','172.16.43.39:443']
        labels:
          framework: 'flask'
          service: 'auth'

  - job_name: 'chatd_exporter'
    metrics_path: /api/chatd/1.0/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.16.43.33:443', '172.16.43.242:443', '172.16.43.141:443', '172.16.43.193:443','172.16.43.39:443']
        labels:
          framework: 'flask'
          service: 'chatd'

  - job_name: 'sysconfd_exporter'
    metrics_path: /api/sysconfd/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.16.43.33:443', '172.16.43.242:443', '172.16.43.193:443', '172.16.43.141:443','172.16.43.39:443']
        labels:
          framework: 'fastapi'
          service: 'sysconfd'


  - job_name: 'wazo-router'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['10.41.0.7:9999', '172.16.43.235:9999']
        labels:
          service: 'wazo-router'

  - job_name: 'kamailio'
    metrics_path: /kamailio/metrics
    scheme: https
    static_configs:
      - targets: ['quintana.wazo.community:443']
        labels:
          service: 'kamailio'

  - job_name: redis_exporter
    static_configs:
    - targets: ['172.16.43.193:9121', '172.16.43.141:9121']
