FROM wazo-trafgen-sipp:0.0.1

RUN apt-get update && apt-get install -y git python2 python-jinja2 

RUN rm /usr/local/bin/python && \
    ln -s /usr/bin/python2.7 /usr/local/bin/python 

WORKDIR /trafgen

RUN  git clone https://github.com/wazo-platform/xivo-load-tester.git
COPY load-tests.sh load-tests.sh
WORKDIR /
