services:
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/elastic-docker/es-data:/usr/share/elasticsearch/data
      - /opt/elastic-docker/es-logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elk.load.wazo.io:9200
      ELASTICSEARCH_HOSTS: http://elk.load.wazo.io:9200
    ports:
      - 5601:5601
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro
    networks:
      - elastic

volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge
