#!/bin/bash

apt-get update
apt-get upgrade -y
mkdir -p src bin /etc/apt/keyrings

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install -y \
	tmux \
	ca-certificates \
	curl \
	gnupg \
	lsb-release \
	curl \
	wget \
	git \
	jq \
	vim \
	docker-ce \
	docker-ce-cli \
	containerd.io \
	docker-compose-plugin \
	python3-pip

cd src && git clone https://github.com/wazo-platform/xivo-load-tester.git
