#!/bin/bash

wget  -P /etc/systemd/system https://raw.githubusercontent.com/moby/moby/master/contrib/init/systemd/docker.service 
wget  -P /etc/systemd/system https://raw.githubusercontent.com/moby/moby/master/contrib/init/systemd/docker.socket


systemctl enable docker.socket
systemctl start docker.socket
systemctl enable docker.service
systemctl start docker.service