#!/bin/bash

cp nginx-metrics /etc/nginx/sites-available/nginx-metrics && 
ln -s /etc/nginx/sites-available/nginx-metrics /etc/nginx/sites-enabled/nginx-metrics 

nginx -s reload

cat <<EOF >/etc/systemd/system/nginx_exporter.service
[Unit]
Description=Nginx Exporter
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=-/usr/bin/docker stop %n
ExecStartPre=-/usr/bin/docker rm %n
ExecStartPre=/usr/bin/docker pull nginx/nginx-prometheus-exporter:0.10.0

ExecStart=docker run --net=host nginx/nginx-prometheus-exporter:0.10.0 -nginx.scrape-uri=http://127.0.0.1:8080/status &


[Install]
WantedBy=multi-user.target
EOF

systemctl enable nginx_exporter
systemctl start nginx_exporter