#!/bin/bash

cat <<EOF >/etc/systemd/system/process_exporter.service
[Unit]
Description=Process Exporter
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull ncabatoff/process-exporter
ExecStart=docker run -d --name process-exporter --rm -p 9256:9256 --privileged -v /proc:/host/proc -v /root/exporters:/config ncabatoff/process-exporter --procfs /host/proc -config.path /config/process.yml
#ExecStop=docker stop process-exporter && docker rm process-exporter

[Install]
WantedBy=multi-user.target
EOF

systemctl enable process_exporter
systemctl start process_exporter

curl localhost:9256/metrics
