{
 "title": "NGINX - Prometheus Exporter",
 "description": "dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "load-run"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(nginx_up, testid)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_up{testid=~\"$testid\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{instance=\"$instance\",testid=~\"$testid\"}[1m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "rate(nginx_connections_handled{instance=\"$instance\",testid=~\"$testid\"}[1m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"$instance\",testid=~\"$testid\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=\"$instance\",testid=~\"$testid\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"$instance\",testid=~\"$testid\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=\"$instance\",testid=~\"$testid\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"$instance\",testid=~\"$testid\"}[1m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}