{
 "title": "OpenSIPS",
 "tags": [ "opensips" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(opensips_up, instance)"
   },
   {
    "name": "process",
    "label": "SER process",
    "query": "label_values(opensips_up, process)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "OpenSIPS meta metrics - $process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "process"
  },
  {
   "title": "OpenSIPS status",
   "type": "stat",
   "description": "Did the OpenSIPS Management Interface respond to our queries?",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "opensips_up{process=~\"$process\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Scrape status",
   "type": "stat",
   "description": "Is the scrape successful?",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"opensips\", instance=~\"$node\", process=\"$process\"}"
    }
   ]
  },
  {
   "title": "CPU Usage exporter",
   "type": "stat",
   "description": "How much CPU does the OpenSIPS exporter use?",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$node\",job=\"opensips\", process=~\"$process\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=~\"$node\",job=\"opensips\", process=~\"$process\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=~\"$node\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage exporter",
   "type": "stat",
   "description": "How much memory does the OpenSIPS exporter use?",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$node\",job=\"opensips\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "stat",
   "description": "How long has the OpenSIPS exporter been up and running?",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$node\",job=\"opensips\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "OpenSIPS uptime",
   "type": "stat",
   "description": "How long has the OpenSIPS process been running?",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensips_core_uptime_seconds{instance=~\"$node\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used exporter",
   "type": "stat",
   "description": "How many File Descriptors is the OpenSIPS exporter currently using?",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$node\",job=\"opensips\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "OpenSIPS load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "System - Processes executing in kernel mode",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~\"$node\",job=~\"node\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Percentage of children processing messages",
     "type": "timeseries",
     "description": "Percentage of UDP/TCP children that are awake and processing SIP messages.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "opensips_load_load{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "{{protocol}} children processing on {{ip}}:{{port}}  - {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_tcp_load{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "TCP children processing  - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Load per OpenSIPS process (current, 1m, 10m)",
     "type": "timeseries",
     "description": "The realtime load per process ID.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "opensips_load_process{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Current load process {{exported_process}} for {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_10m{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "10m load process {{exported_process}} for {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_1m{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "1m load process {{exported_process}} for {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "OpenSIPS core process load",
     "type": "timeseries",
     "description": "The realtime load of entire OpenSIPS - this counts all the core processes of OpenSIPS; the additional processes requested by modules are not counted in this load.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "opensips_load_core{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Core load for {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_core_1m{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Core load 1m for {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_core_10m{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Core load 10m for {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Load of all processes",
     "type": "timeseries",
     "description": "The realtime load of entire OpenSIPS, counting both core and module processes.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "opensips_load_all{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "All load for for {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_all_1m{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "All load 1m for for {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_load_all_10m{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "All load 1m for {{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Memory Free (private memory) - $interval interval",
     "type": "timeseries",
     "description": "What percentage of private memory is still free for a particular PID to use?",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "(avg_over_time(opensips_pkmem_free_size{instance=~\"$node\", process=~\"$process\"}[$interval]) / avg_over_time(opensips_pkmem_total_size{instance=~\"$node\", process=~\"$process\"}[$interval])) * 100",
       "legendFormat": "PID {{pid}} - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "% Memory Free (shared memory) - $interval interval",
     "type": "timeseries",
     "description": "What percentage of shared memory is still free to use?",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "(avg_over_time(opensips_shmem_free_size{instance=~\"$node\", process=~\"$process\"}[$interval]) / avg_over_time(opensips_shmem_total_size{instance=~\"$node\", process=~\"$process\"}[$interval])) * 100",
       "legendFormat": "{{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage by PID (private memory)",
     "type": "timeseries",
     "description": "Breakdown of memory usage by PID.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "opensips_pkmem_real_used_size{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "PID {{pid}} - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage (shared memory)",
     "type": "timeseries",
     "description": "How much shared memory does the OpenSIPS process use?",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "opensips_shmem_real_used_size{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "{{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Private memory fragments",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "max(opensips_pkmem_fragments{instance=~\"$node\", process=~\"$process\"}) without (pid)",
       "legendFormat": " {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Shared Memory fragments",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "opensips_shmem_fragments{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "{{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS replies/requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of replies ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(opensips_sl_replies{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{type}} reply - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_sl_sent_err_replies_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Sent error replies - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_sl_sent_replies_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Total sent replies - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_sl_failures{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Reply failures - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_sl_xxx_replies{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "XXX Replies - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of received requests by OpenSIPS ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "rate(opensips_core_requests_total{process=~\"$process\", instance=~\"$node\"}[$interval])",
       "legendFormat": "Total request received - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_core_requests{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{kind}} request - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of received replies by OpenSIPS ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(opensips_core_replies_total{process=~\"$process\", instance=~\"$node\"}[$interval])",
       "legendFormat": "Total replies received - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_core_replies{process=~\"$process\", instance=~\"$node\"}[$interval])",
       "legendFormat": "{{kind}} replies received - {{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS netstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes waiting for consumption",
     "type": "timeseries",
     "description": "Number of bytes waiting to be consumed on an interface that OpenSIPS is listening on.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "opensips_net_waiting{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Bytes waiting ({{protocol}}) - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes{instance=~\"$node\",job=~\"node\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes{instance=~\"$node\",job=~\"node\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS dialogs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dialog rate per status ($interval)",
     "type": "timeseries",
     "description": "Rate of dialogs and what the status of the dialog was.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(opensips_dialog_dialogs{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Dialog {{status}} - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Dialogs sent/receive rate from other OpenSIPS instances",
     "type": "timeseries",
     "description": "The number of dialog events received from other OpenSIPS instances.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(opensips_dialog_received{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Dialog received - {{event}} - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_dialog_sent{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Dialog sent - {{event}} - {{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction reply received rate by type ($interval)",
     "type": "timeseries",
     "description": "How many transaction replies per second were received? And what was their response type? (2xx, 3xx, etc.)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(opensips_tm_transactions_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{type}} transaction - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction reply rate ($interval)",
     "type": "timeseries",
     "description": "How many replies were received per second? Were they generated locally? Relayed?",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "rate(opensips_tm_local_replies_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Local replies - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_tm_received_replies_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Received replies - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_tm_relayed_replies_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Relayed replies - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Current transactions in memory",
     "type": "timeseries",
     "description": "How many transactions are in memory?",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "opensips_tm_inuse_transactions{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Transactions in memory - {{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kamailio transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction reply received rate by type ($interval)",
     "type": "timeseries",
     "description": "How many transaction replies per second were received? And what was their response type? (2xx, 3xx, etc.)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(opensips_tmx_transactions_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{type}} transaction - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_tmx_UAS_transactions{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "UAS transaction - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Current transactions",
     "type": "timeseries",
     "description": "How many transactions are in memory or ongoing at the moment?",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "opensips_tmx_inuse_transactions{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Transactions in memory - {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_tmx_active_transactions{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Transactions ongoing - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction reply rate by action ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(opensips_tmx_replies{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Transaction reply {{type}} - {{process}}@{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error rate ($interval)",
     "type": "timeseries",
     "description": "What is the rate of errors per second?",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate(opensips_core_bad_URIs_rcvd{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "URI parse errors - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_core_bad_msg_hdr{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "SIP Header parse errors - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_core_unsupported_methods{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "Unsupported method - {{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS URI module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "URI Checks rate ($interval)",
     "type": "timeseries",
     "description": "How many URI checks have happened? Were they positive or negative?",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(opensips_uri_negative_checks{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "URI negative checks - {{process}}@{{instance}}"
      },
      {
       "expr": "rate(opensips_uri_positive_checks{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": "URI positive checks - {{process}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSIPS User Location module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "User registration rate ($interval)",
     "type": "timeseries",
     "description": "Total number of AOR existing in the USRLOC memory cache for all domains per second.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(opensips_userloc_registered_users_total{instance=~\"$node\", process=~\"$process\"}[$interval])",
       "legendFormat": " Registered users - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Users per domain",
     "type": "timeseries",
     "description": "Number of contacts/expired users/total users existing in the USRLOC memory cache per domain.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "opensips_usrloc_contacts{instance=~\"$node\",process=~\"$process\"}",
       "legendFormat": "Contacts in {{domain}} - {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_usrloc_users{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Total users in {{domain}} - {{process}}@{{instance}}"
      },
      {
       "expr": "opensips_usrloc_expires{instance=~\"$node\", process=~\"$process\"}",
       "legendFormat": "Expired contacts in {{domain}} - {{process}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Total users in $process",
     "type": "stat",
     "description": "Total number of AOR existing in the USRLOC memory cache for all domains.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "repeat": "process",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensips_userloc_registered_users_total{instance=~\"$node\", process=~\"$process\"}"
      }
     ]
    }
   ]
  }
 ]
}