{
 "title": "Wazo - Asterisk Simple",
 "tags": [
  "wazo",
  "asterisk",
  "load-run"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "testid",
    "label": "Test ID",
    "query": {
     "query": "label_values(asterisk_bridges_count, testid)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(asterisk_bridges_count{testid=~\"$testid\"}, instance)\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://theme.zdassets.com/theme_assets/1871843/c8e815188e147f36375d3f4e52c2fb25558b1dec.png\"\n     alt=\"Wazo Icone\"\n     style=\"float: left; margin: 10px;\" />\n\n \n           "
   }
  },
  {
   "title": "Asterisk Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{instance=\"$instance\",testid=~\"$testid\",job=\"asterisk\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Asterisk core Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_uptime_seconds{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Asterisk core last reload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_last_reload_seconds{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Asterisk core scrape time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_scrape_time_ms{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Simultaneous Active Calls / Channels / Bridges Historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=\"$instance\",testid=~\"$testid\"}"
    },
    {
     "expr": "asterisk_channels_count{instance=\"$instance\",testid=~\"$testid\"}"
    },
    {
     "expr": "asterisk_bridges_count{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Current Active Calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Max Calls over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(asterisk_calls_count{instance=\"$instance\",testid=~\"$testid\"}[1d])"
    }
   ]
  },
  {
   "title": "Current Active Channels",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_channels_count{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Max Channels over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(asterisk_channels_count{instance=\"$instance\",testid=~\"$testid\"}[1d])"
    }
   ]
  },
  {
   "title": "Current Active Bridges",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_bridges_count{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Max Bridges over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(asterisk_bridges_count{instance=\"$instance\",testid=~\"$testid\"}[1d])"
    }
   ]
  },
  {
   "title": "Current online Endpoints",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(asterisk_endpoints_state{instance=\"$instance\",testid=~\"$testid\"}==2)"
    }
   ]
  },
  {
   "title": "Max Endpoints over the day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(count(asterisk_endpoints_state{instance=\"$instance\",testid=~\"$testid\"}==2)[1d:10m])"
    }
   ]
  },
  { "title": "Endpoints Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Online Endpoints Historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(asterisk_endpoints_state{instance=\"$instance\",testid=~\"$testid\"}==2)"
    }
   ]
  },
  {
   "title": "Current Endpoints State (0=unknown; 1=offline; 2=online)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(asterisk_endpoints_state{instance=\"$instance\",testid=~\"$testid\"}==0) or vector(0)",
     "legendFormat": "Endpoints Unknown"
    },
    {
     "expr": "count(asterisk_endpoints_state{instance=\"$instance\",testid=~\"$testid\"}==1) or vector(0)",
     "legendFormat": "Endpoints Offline"
    },
    {
     "expr": "count(asterisk_endpoints_state{instance=\"$instance\",testid=~\"$testid\"}==2) or vector(0)",
     "legendFormat": "Endpoint Online"
    }
   ]
  },
  {
   "title": "Current defined Endpoints",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_endpoints_count{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Evolution of Defined Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "asterisk_endpoints_count{instance=\"$instance\",testid=~\"$testid\"}"
    }
   ]
  }
 ]
}