{
 "title": "Wazo - Flask Services",
 "tags": [ "wazo" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "testid",
    "label": "Test ID",
    "query": {
     "query": "label_values(python_info, testid)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(python_info{testid=~\"$testid\"}, instance)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(flask_http_request_total, method)"
    }
   },
   {
    "name": "return_code",
    "query": {
     "query": "label_values(flask_http_request_total, status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests per minute - all methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{instance=\"$instance\",testid=~\"$testid\"}[1m])",
     "legendFormat": "{{service}} {{status}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(flask_http_request_duration_seconds_count{status!~\"200|201|204\", method=~\"$method\", instance=\"$instance\",testid=~\"$testid\"}[30s]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[1m])",
     "legendFormat": "HTTP {{ status }} {{ service }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"$return_code\", method=~\"$method\", instance=\"$instance\",testid=~\"$testid\"}[30s])",
     "legendFormat": "{{ service }} ({{ endpoint }})"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"$return_code\", instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[30s]) / rate(flask_http_request_duration_seconds_count{status=\"$return_code\", instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[30s])",
     "legendFormat": "{{ service }} ({{ endpoint }})"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (service, endpoint) (increase(flask_http_request_duration_seconds_bucket{le=\"0.25\", instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[30s])) / sum by (service, endpoint) (increase(flask_http_request_duration_seconds_count{instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[30s]))",
     "legendFormat": "{{ service }} ({{ endpoint }})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\",testid=~\"$testid\", service=~\"wazo-.+\"}[30s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",testid=~\"$testid\", service=~\"wazo-.+\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, service, endpoint) (rate(flask_http_request_duration_seconds_bucket{instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[30s])))",
     "legendFormat": "{{ service }} ({{ endpoint }})"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, service, endpoint) (rate(flask_http_request_duration_seconds_bucket{instance=\"$instance\",testid=~\"$testid\", method=~\"$method\"}[30s])))",
     "legendFormat": "{{ service }} ({{ endpoint }})"
    }
   ]
  }
 ]
}