#cloud-config
runcmd:
  - echo 'Mounting volume...'
  - mkdir /mnt/prometheus
  # Workaround: Volumes are not always detected in the same order
  - mount /dev/sda /mnt/prometheus || mount /dev/sdb /mnt/prometheus
  - chmod 777 /mnt/prometheus

  - echo 'Installing docker...'
  - apt-get update
  - apt-get install -y ca-certificates curl gnupg
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  - echo 'Installing grizzly...'
  - curl -fSL -o "/usr/local/bin/grr" "https://github.com/grafana/grizzly/releases/download/v0.7.1/grr-linux-amd64"
  - chmod a+x "/usr/local/bin/grr"
