{
 "title": "Process Exporter",
 "description": "This dashboard is another version of Named processes dashboard",
 "tags": [ "process" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process exporter status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\", job=\"process\"}"
    }
   ]
  },
  {
   "title": "proportional resident memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=\"$instance\", memtype=\"proportionalResident\"} > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]) )without (mode) > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=\"$instance\", memtype=\"resident\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "num processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{instance=\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=\"$instance\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "voluntary context switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=\"$instance\", ctxswitchtype=\"voluntary\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "nonvoluntary context switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=\"$instance\", ctxswitchtype=\"nonvoluntary\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{instance=\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "major page faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_major_page_faults_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "minor page faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_minor_page_faults_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "uptime(oldest)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (avg by (groupname) (namedprocess_namegroup_oldest_start_time_seconds{instance=\"$instance\"} > 0))",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}